name: Build LaTeX document
on: [push]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: {{cookiecutter.file_name}}.tex
          post_compile: "mkdir build && mv {{cookiecutter.file_name}}.pdf build"
      - name: Deploy PDF
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pdf
          folder: build

